### ISSUE TITLE
打开应用后会关闭cpu核心

### ISSUE THREAD

**Issue by FrzMtrsprt** [brandonw3612/LyricEase#1]
打开应用后，四个cpu核心中一个的占用会立刻下降到5%以下，并且关闭应用后仍然如此，重启电脑才能恢复。每次必出现。

**Comment by brandonw3612** [comment]
UWP软件没有影响系统级资源调度的权限. 如果是占用过高我们也许可以修复. 系统资源调度方面的问题建议找微软.

**Comment by FrzMtrsprt** [comment]
好的
