### ISSUE TITLE
[BUG] 播放部分歌单时闪退

### ISSUE THREAD

**Issue by lau0511** [brandonw3612/LyricEase#10]
## 错误描述
播放歌单"Play All"时软件闪退

## 复现步骤
1. 前往 Pick For You页面
2. 随便点击一个歌单
3. 点击Play All
4. 软件直接闪退

## 预期结果
播放歌单时不再闪退

## Windows 和 LyricEase
 - Windows 版本号 [Windows 10 19044.1469
 - Windows SKU 家庭版 
 - 是否为预览体验计划  否
 - LyricEase 版本号  v0.9.94

**Comment by brandonw3612** [comment]
怀疑为播放核心逻辑有误, 0.10 将调整, 新版本释出后再观察.

**Comment by lau0511** [comment]
收到！谢谢 Sent from Mail for Windows From: Brandon WongSent: Wednesday, 26 January, 2022 9:13 PMTo: brandonw3612/LyricEaseCc: lau0511; AuthorSubject: Re: [brandonw3612/LyricEase] [BUG] 软件闪退 (Issue #10) 怀疑为播放核心逻辑有误, 0.10 将调整, 新版本释出后再观察.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by lau0511** [comment]
solved
