### ISSUE TITLE
[FEATURE]j建议添加一个最小化至托盘的功能

### ISSUE THREAD

**Issue by youngforblbl** [brandonw3612/LyricEase#102]
## 你的建议
添加一个诸如网易云的最小化托盘的功能，不然的话总在任务栏上在工作时较为占地
## 该建议的实现方式
如图所示：
![image](https://user-images.githubusercontent.com/57397382/171798467-6f0763a6-f961-4589-bd7a-b47069da8379.png)

## 附加信息
再托盘上右键可以打开小菜单进行切歌、暂停等功能

**Comment by kengwang** [comment]
请勿发送无内容 Issue，烦请填写好相关内容后再发

**Comment by youngforblbl** [comment]
> 请勿发送无内容 Issue，烦请填写好相关内容后再发

改完了，就是希望能有一个托盘化的功能

**Comment by kengwang** [comment]
Dup #20 
Please Refer: https://github.com/brandonw3612/LyricEase/issues/20#issuecomment-1030868755

**Comment by kengwang** [comment]
PS: 可以参考这个视频来实现类似的样式
https://www.bilibili.com/video/BV1SY411j7E2?t=194.7
