### ISSUE TITLE
[BUG] 有时候启动会卡logo不能进入，需要重置应用数据

### ISSUE THREAD

**Issue by azxiaosen** [brandonw3612/LyricEase#105]
-->

## 错误描述
如题

## 复现步骤
无规律，有时启动就这样

## 预期结果
期望修复

## 屏幕截图 / 屏幕录制
无

## 设备, Windows 和 LyricEase
 - 设备型号  :DELL G15 5511
 - Windows 版本号 Windows 10 19044.1741]
 - Windows SKU 专业版 
 - 是否为预览体验计划 否: 
 - LyricEase 版本号 v0.11.16

**Comment by brandonw3612** [comment]
Duplicate of #81￼
