### ISSUE TITLE
[FEATURE] 能否将此箭头标志改为居中

### ISSUE THREAD

**Issue by WTYJ** [brandonw3612/LyricEase#106]
能否将如图的全屏模式歌曲详情页正上方的小箭头改为居于全页正中，这样可能看着更美观
![1](https://user-images.githubusercontent.com/64718702/174449369-1c0041aa-f5da-4ca3-904c-c7cc2b3be4c8.png)

**Comment by brandonw3612** [comment]
播放视图会在今年优化一次，改动较大，新视图会调整这些问题。当前视图布局不会修改。
