### ISSUE TITLE
使用网易邮箱登录时出现错误 -462

### ISSUE THREAD

**Issue by balthild** [brandonw3612/LyricEase#107]
## 错误描述

使用网易邮箱登录时出现错误 -462

## 复现步骤

1. 打开软件
2. 点击“使用网易邮箱登录”
3. 输入邮箱
4. 输入密码
5. 点击“登录”

## 预期结果

登录成功

## 屏幕截图 / 屏幕录制

![image](https://user-images.githubusercontent.com/2662758/174473142-59d34bd4-455b-43db-9fcd-7b004c56f538.png)

## 设备, Windows 和 LyricEase
 - 设备型号 : ASUS TUF Dash F15 FX516PM_FX516PM
 - Windows 版本号 : 10.0.19044 内部版本 19044
 - Windows SKU : 专业版
 - 是否为预览体验计划 : 否
 - LyricEase 版本号 : v0.11.116

**Comment by brandonw3612** [comment]
请更新至 `v0.11.118` 版本后查看能否正常登录账号。

**Comment by balthild** [comment]
能正常登录了
