### ISSUE TITLE
[BUG] 无法链接到last.fm

### ISSUE THREAD

**Issue by HAMAN23333** [brandonw3612/LyricEase#108]
## 错误描述

无法链接到last.fm

## 复现步骤

1. 打开软件
2. 点击链接到last.fm的“链接账户”按钮
3. 输入邮箱和密码
4. 点击链接

## 预期结果

成功链接

## 屏幕截图 / 屏幕录制

![image](https://user-images.githubusercontent.com/80085265/175050207-8a2b9beb-c59d-43a9-8809-fb4972f30fc8.png)

## 设备, Windows 和 LyricEase
 - 设备型号  : MS-7A40
 - Windows 版本号  : Windows 11 22000.739
 - Windows SKU  : 专业版
 - 是否为预览体验计划  : 否
 - LyricEase 版本号  : 0.11.116

**Comment by brandonw3612** [comment]
Last.fm API 限制，仅可使用用户名 + 密码登录。下一版会做出说明修正。

**Comment by HAMAN23333** [comment]
了解了
