### ISSUE TITLE
[FEATURE] 返回按钮的显示和隐藏

### ISSUE THREAD

**Issue by NalCol** [brandonw3612/LyricEase#111]
## 你的建议
返回按钮采用“有上一级界面时出现”而不是“固定显示，以可点按状态区分”。
## 该建议的实现方式
没有上一级界面时，用滑出动画将返回按钮移出界面，同时附带透明度减弱效果。以哔哩为例：
<video src="https://user-images.githubusercontent.com/58576200/175751763-66bd141d-8618-43d4-937c-9034ae14d56d.mp4" controls>
  你的浏览器不支持 <code>video</code> 标签。
</video>

**Comment by brandonw3612** [comment]
参考 https://github.com/microsoft/WinUI-Gallery
