### ISSUE TITLE
[BUG] icon的异常位移

### ISSUE THREAD

**Issue by NalCol** [brandonw3612/LyricEase#112]
## 错误描述
左上角LyricEase icon有异常表现，隐藏菜单时icon会向右移动，但是并没有内容填充到移动产生的空隙中，如视频所示。

## 复现步骤
点击菜单键隐藏菜单

## 预期结果
不产生位移，或将#111 的行为方式加入

## 屏幕截图 / 屏幕录制
<video src="https://user-images.githubusercontent.com/58576200/175751890-c2e2ebf9-163d-4249-961b-7fed1386c8e8.mp4" controls>
</video>

## 设备, Windows 和 LyricEase
 - 设备型号: MS-7C94
 - Windows 版本号: Windows 11 22000.739
 - Windows SKU: 专业版
 - 是否为预览体验计划: 否
 - LyricEase 版本号: 0.11.119

**Comment by brandonw3612** [comment]
参考 https://github.com/microsoft/WinUI-Gallery
