### ISSUE TITLE
[FEATURE] 关于部分 UI / UX 的建议

### ISSUE THREAD

**Issue by kengwang** [brandonw3612/LyricEase#12]
## 你的建议

- [ ] 歌单页面进入时如果图片从 未加载出来 -> 加载出来 时会导致 Header 的高度发生变化, 进而导致下部 UI 会下沉

## 该建议的实现方式

1. 可以固定好图片这个的高度, 在未加载完成时就占用这个高度

## 附加信息

这是个人的有些用着感觉有些打断 flow 的细节
有其他的会进行叠楼

**Comment by kengwang** [comment]
- [ ] 对于纯音乐的歌词将「纯音乐,请欣赏」恒不模糊
![image](https://user-images.githubusercontent.com/30862240/151669657-9d19328e-22d2-446c-8ee9-454085925c93.png)

**Comment by brandonw3612** [comment]
> [ ] 对于纯音乐的歌词将「纯音乐,请欣赏」恒不模糊
> ![image](https://user-images.githubusercontent.com/30862240/151669657-9d19328e-22d2-446c-8ee9-454085925c93.png)

2月1日 v0.10 更新修复

**Comment by brandonw3612** [comment]
> 可以固定好图片这个的高度, 在未加载完成时就占用这个高度

下次更新解决

**Comment by brandonw3612** [comment]
先关了，避免 issue 重复。此后每个问题单独开 issue。
