### ISSUE TITLE
检查更新对话框显示空白

### ISSUE THREAD

**Issue by Gaoyifei1011** [brandonw3612/LyricEase#14]
检查更新对话框显示空白，希望修复一下这个问题
![image](https://user-images.githubusercontent.com/49179966/151806098-ec8612c8-ba92-4811-b84a-43b0e3369f2f.png)

**Comment by brandonw3612** [comment]
新版修正. 最后发现不是微软的锅, 是我们语言资源文件填写错了😂.

**Comment by brandonw3612** [comment]
v0.10.102 已解决
