### ISSUE TITLE
亚克力效果消失了？

### ISSUE THREAD

**Issue by PIndividual** [brandonw3612/LyricEase#15]
## 错误描述
我在现在的版本里已经无法看到亚克力效果了，即使使用高级视觉效果的选项已经启用

## 复现步骤
 :Windows 10 21H2 19044.1503
 - Windows SKU  :专业工作站版
 - 是否为预览体验计划  : 是
 - LyricEase 版本号  :0.10.99

**Comment by PIndividual** [comment]
![image](https://user-images.githubusercontent.com/62368342/151906486-adc2592e-afcc-4384-bb97-b00aa65e3089.png)

**Comment by brandonw3612** [comment]
您提的另一个issue也是同样问题.

**Comment by brandonw3612** [comment]
亚克力材质的显示是受系统和软件同时控制的. 如需启用亚克力材质, 请确保以下条件已满足:

1. 设备硬件本身支持视觉效果显示, 否则为正常显示请在设置中将 "性能与体验" 选择为 "更佳性能";
2. 设置 - 个性化 - 颜色 - 透明效果已启用;
3. 设备不处于省电模式;
4. LyricEase 设置中 "性能与体验" 设置为 "平衡" 或 "更佳效果".

**Comment by brandonw3612** [comment]
此问题属于系统配置，无需软件端做出改动。
