### ISSUE TITLE
[BUG] 点击“私人FM”，短暂卡顿后直接闪退

### ISSUE THREAD

**Issue by WTYJ** [brandonw3612/LyricEase#18]
复现步骤
1. 点击“私人FM”
2. 短暂卡顿后直接闪退

预期结果
正常使用该功能

屏幕截图 / 屏幕录制

https://user-images.githubusercontent.com/64718702/151953648-3dca9085-0357-41a3-9c66-7f4c288ada09.mp4

Windows 和 LyricEase
 - Windows 版本号 <Windows 11 22543.1000> 
 - Windows SKU <专业版> 
 - 是否为预览体验计划 <是> 
 - LyricEase 版本号 <v0.10.99> 

附加信息
本人较少使用Github，关于bug请见附件（录屏），无法及时回复请谅解

**Comment by KrisowX** [comment]
一样，正式版22000.469同样有这个问题。

**Comment by brandonw3612** [comment]
那么问一下，两位个性推荐功能是否正常呢？
@WTYJ @KrisowX

**Comment by WTYJ** [comment]
关闭了个性话推荐，因为和隐私相关




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Brandon ***@***.***&gt;; 
发送时间: 2022年2月1日(星期二) 晚上9:34
收件人: ***@***.***&gt;; 
抄送: "Dream.SKY ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [brandonw3612/LyricEase] [BUG] 点击“私人FM”，短暂卡顿后直接闪退 (Issue #18)





 
那么问一下，两位个性推荐功能是否正常呢？
 @WTYJ @KrisowX
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brandonw3612** [comment]
> 关闭了个性话推荐，因为和隐私相关
> […](#)

好的，网易服务器那边对关闭个性推荐的用户发送的私人FM请求是不会返回任何数据的，所以这边我们也无法提供相关服务，编写这一块时确实没有考虑这个问题，我们会调整代码提示用户而不是闪退。

**Comment by KrisowX** [comment]
我这里个性推荐处于打开状态，经测试必须要先打开个性推荐页面，并在个性推荐放一首歌之后才能够打开私人FM而不闪退，否则私人FM仍会闪退。

**Comment by brandonw3612** [comment]
@WTYJ @KrisowX 可否更新v0.10.102版本后反馈一下情况？
