### ISSUE TITLE
拔出耳机后再插入无法播放

### ISSUE THREAD

**Issue by KiritoKing** [brandonw3612/LyricEase#2]
拔出耳机后（包括断开蓝牙耳机后重连）会自动停止播放 重新连接后按播放键也没有反应 重新启动应用可解决
其他非UWP播放器（网易云Win32官方）和UWP播放器（QQ音乐UWP官方）都没有这个问题

**Comment by brandonw3612** [comment]
软件版本是v0.9.94？

**Comment by KiritoKing** [comment]
刚刚微软商店推更新了 测了下好像没有了 再观察下
 上个版本稳定复现

**Comment by brandonw3612** [comment]
> 刚刚微软商店推更新了 测了下好像没有了 再观察下
> 上个版本稳定复现

抱歉刚看到回复. 解决就好.
