### ISSUE TITLE
[FEATURE] 私人FM提供快速收藏功能

### ISSUE THREAD

**Issue by WuJunkai2004** [brandonw3612/LyricEase#21]
## 你的建议
私人FM播放时无`播放上一首`的选项，可否在原本`上一首`图标处替换为收藏键，方便听到喜欢的歌时收藏。

## 该建议的实现方式
目前无已实现的例子，稍微P个图，表现一下大概的意思。

![issue.png](https://s2.loli.net/2022/02/09/osbCTep9kFDBKO7.png)

## 附加信息
无

**Comment by kengwang** [comment]
网易云音乐的 APP 以及 电脑端 均无上一曲选项, 此功能可能不太必要

**Comment by brandonw3612** [comment]
> 网易云音乐的 APP 以及 电脑端 均无上一曲选项, 此功能可能不太必要

这位同学 注意审题

**Comment by kengwang** [comment]
按理说可以点更多来进行收藏的
![image](https://user-images.githubusercontent.com/30862240/153355247-eb6bee34-bba5-414e-b890-6e059d058f7b.png)

不过手机APP上的操作确实是吧上一首弄成喜欢的

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/153355706-c01482cb-84da-4c5d-b8a3-bb1b3fdde1e3.png)

顺, 表演者后面的括号是想展示译名吗?

**Comment by brandonw3612** [comment]
> 顺, 表演者后面的括号是想展示译名吗?

FM那块数据有点异常，在调

**Comment by brandonw3612** [comment]
0.10.105 已完成
