### ISSUE TITLE
桌面歌词能不能实现

### ISSUE THREAD

**Issue by lyf1995211** [brandonw3612/LyricEase#23]
桌面歌词能不能实现，类似Hyplayer也行。
![image](https://user-images.githubusercontent.com/22750079/153692120-f8bf18ef-5492-4369-8157-284c14f16a19.png)

**Comment by brandonw3612** [comment]
除非 UWP 体系大改或者 WinUI 3 达到预期, 否则不会做.
这边先关闭 issue 了, 如果后期有计划会重开讨论.

**Comment by brandonw3612** [comment]
v.0.11.114 已通过辅助应用《热词》实现桌面歌词。

**Comment by lyf1995211** [comment]
感谢！提个小建议，如果能搞了开关打开后只要播放就自动启动热词应用就更加完美了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Brandon ***@***.***>
发送时间: 2022年3月28日 12:48
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [brandonw3612/LyricEase] 桌面歌词能不能实现 (Issue #23)


Closed #23<https://github.com/brandonw3612/LyricEase/issues/23>.

―

**Comment by brandonw3612** [comment]
> 感谢！提个小建议，如果能搞了开关打开后只要播放就自动启动热词应用就更加完美了

现在有开关啊

**Comment by lyf1995211** [comment]
嗯嗯，装完软件刚才打开设置看到了，不好意思

发自我的iPhone

在 2022年3月28日，14:44，Brandon Wong ***@***.***> 写道：

﻿

感谢！提个小建议，如果能搞了开关打开后只要播放就自动启动热词应用就更加完美了

现在有开关啊
