### ISSUE TITLE
[BUG] 歌单很多时加载个人页面会卡死一会

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [brandonw3612/LyricEase#26]
## 错误描述
我收藏的歌单很多，每次加载个人页面的时候都会卡转圈加载动画好久，这时候整个App都会无法操控

## 复现步骤
1. 前往歌单数量很多的个人页面
2. 就会出现卡转圈然后卡死很久

## 预期结果
可以使用翻页或者lazyload来缓解吧

## 屏幕截图 / 屏幕录制
https://www.youtube.com/watch?v=qP0nZ-Fm100
（鼠标声音录进去了，可以听一下点击声音）

## Windows 和 LyricEase
 - Windows 版本号  :Windows 10 19044.1526 (21H2)
 - Windows SKU  : 专业工作站版
 - 是否为预览体验计划  : 否
 - LyricEase 版本号  :0.10.102

## 附加信息
还有我喜欢的音乐里曲子很多也以一样的形式卡一会
算是听歌重度用户会碰到的问题吧qwq

**Comment by kengwang** [comment]
同这个问题, 我的歌单不算太多, 卡的时间稍微没那么长
但是在加载歌单的时候确实会卡住 UI 线程无法操作
两种可能:
1. 加载在 UI 线程里面
2. 加载在 async 但是渲染在 UI 线程且渲染过程过于缓慢

**Comment by brandonw3612** [comment]
0.11 版本会尝试修复

**Comment by WindyMadman** [comment]
目前的话不仅是这个问题 收藏的歌单太多了之后会导致缩放窗口出现卡顿 收藏的音太多了也会卡 而且主界面的菜单点一次就卡一秒

**Comment by brandonw3612** [comment]
> 目前的话不仅是这个问题 收藏的歌单太多了之后会导致缩放窗口出现卡顿 收藏的音太多了也会卡 而且主界面的菜单点一次就卡一秒

0.11.108/110 内测已解决此问题。

**Comment by brandonw3612** [comment]
v0.11.114 已修复
