### ISSUE TITLE
[BUG] 软件无法使用代理服务器

### ISSUE THREAD

**Issue by Titantime314** [brandonw3612/LyricEase#29]
## 错误描述

不知道这算不算BUG，但感觉也不是功能建议。本软件无法使用系统的本地代理，此为UWP软件通病，因此采取了faq中给出的解决方法：

>2. 某些版本存在网络代理下无法使用的问题. 请使用 Powershell 运行以下指令: CheckNetIsolation.exe loopbackexempt -a -p=S-1-15-2-3740683252-4218607605-2448778852-3644121063-1212457277-1263217692-2375173846 . 我们后续将支持使用自定义网络代理。

及[为Win10-UWP应用使用设置代理](https://www.jianshu.com/p/41920ec53585)的方法，以解除UWP软件访问localhost的限制 。此方法在其它UWP软件(包括但不限于网易云UWP，OneNote，Minecraft UWP等软件)都可以正常发挥作用，但是在此软件上却无法奏效。

## 复现步骤

使用程序包系列名称或程序包系列安全标识符(SID)将软件加入环回免除列表均无法起效。查询环回免除列表，软件在列表中，但还是无法跟随系统代理，(猜测）仍然使用直连。

## 预期结果

可以使该软件跟随系统整体代理设置，以达到**在不能访问网易云的网络环境下挂代理访问网易云**的效果

## 屏幕截图 / 屏幕录制

报错：
![error1](https://user-images.githubusercontent.com/46022494/154210397-3a15e9cc-52ea-4a15-977f-d7c9250e0e4f.png)
![error2](https://user-images.githubusercontent.com/46022494/154210402-f39d73b1-0705-46ad-8df4-35f35a4d31f7.png)

代理设置：
![proxy_setting](https://user-images.githubusercontent.com/46022494/154210439-10ba3b5b-1a98-427d-8fa6-44a65c53289b.png)

环回免除列表中包含该软件：
![环回免除列表](https://user-images.githubusercontent.com/46022494/154210466-c44e8e21-a249-4d51-b3a8-5a5d65e19259.png)

## Windows 和 LyricEase
 - Windows 版本号 ：Windows 10 19044.1526 
 - Windows SKU ：家庭版 
 - 是否为预览体验计划 ：否 
 - LyricEase 版本号 ：v0.10.103 (20220215) 

## 附加信息

在faq中以及提及的问题原本是不应该发issue的，但是我仔细读了一下感觉faq中描述的是**使用了代理导致软件无法正常访问网易云**的情形而非**在本不能访问网易云的网络下使用代理访问网易云**的情形，所以还是想要发个issue问一下作者大佬。

该需求的场景是公司内网ban掉了网易云、B站等”娱乐网站“，所以我想用自己服务器搭个跳板绕开限制来~~上班摸鱼~~  来提升效率。虽然现在已经可以在公司内网使用网易云UWP了，但还是想用LyricEase，毕竟好看就是第一生产力。

**Comment by brandonw3612** [comment]
我们这边研究一下嗷

**Comment by Titantime314** [comment]
哇塞这也太效率了(#ﾟДﾟ)
可不可以说一下是什么原因导致的，整了我一天都没搞定整得我有点好奇(σ′▽‵)′▽‵)σ

**Comment by brandonw3612** [comment]
应该就是强制不走代理的原因，麻烦您把您代理的方式描述一下，我这边测试一下。
也可以邮箱联系具体事项：brandonw3612@outlook.com

**Comment by susanforme** [comment]
> 
可以使用clash的uwp应用网路回环解决。开发者应该是没办法的向本地发送流量

**Comment by FinaFina233** [comment]
cmd里面输入
CheckNetIsolation.exe loopbackexempt -a -p=S-1-15-2-3740683252-4218607605-2448778852-3644121063-1212457277-1263217692-2375173846
就可以了 很简单的

**Comment by brandonw3612** [comment]
> 推断是否与issue[BUG] 无法联网 #36产生矛盾

确实矛盾了. 0.10.104-0.10.105 的确改了这块.

本来我以为0.10.104没弄成呢...如果昨天告诉我解决了我就不改了🥲后面我们给个选项来设置就好. 这周推送出来. 不急.

**Comment by brandonw3612** [comment]
> 给个v0.10.104的包

刚好有个 0.10.104 的备份

[这里](https://www.icloud.com.cn/iclouddrive/087gFQ-UqsBVyCC3_wuDxDl2A#17588BrandonWong.LyricEase_0.10.104)是安装包的 iCloud 链接，国内可直接下载。

**Comment by Titantime314** [comment]
因为昨天晚上才看到更新，当时已经下班了公司的block解除了所以也没意识到弄成了😂

今天上班点进去试了一下才发现可以了，想进来关掉这个issue的时候发现了#36提到的问题，就想难不成是因为修了我这个需求造成的？

结果一更新0.10.105版本..果不其然又变回去了🤣

>后面我们给个选项来设置就好

好耶，原来可以我全都要！但是还是感觉很神奇，其它UWP软件好像也没遇到过这种情况，难不成是API那边的问题？

**Comment by brandonw3612** [comment]
#36 的问题不一定是代理造成，和本机网络环境、设置等都会有关系。

**Comment by brandonw3612** [comment]
就这两天了
<img width="474" alt="Screen Shot 2022-03-04 at 9 53 48 AM" src="https://user-images.githubusercontent.com/29965003/156684154-d38b26f4-28e9-4c52-996f-bf6985b55f07.png">

**Comment by brandonw3612** [comment]
已推送. 更新后请反馈.

**Comment by Titantime314** [comment]
>已推送. 更新后请反馈.
V0.10.106 原问题已解决

---

另，在开启系统代理的时候选择使用自定义代理设置（即Windows在设置中开启了代理，但软件选择的是自定义代理），软件还是会跟随系统代理，这是正常现象吗？

**Comment by brandonw3612** [comment]
调查一下，此issue关闭.
