### ISSUE TITLE
[BUG] 无法登录

### ISSUE THREAD

**Issue by QuickXand** [brandonw3612/LyricEase#3]
## 错误描述

无法登录

## 预期结果

无法登录

## 屏幕截图 / 屏幕录制

![屏幕截图(1)](https://user-images.githubusercontent.com/96399652/146700264-26da906c-5770-400c-b973-7480a4850a36.png)

## Windows 和 LyricEase
 - Windows 版本号  :
 - Windows 11 22000.376
 - Windows SKU  :
 - 家庭版
 - 是否为预览体验计划  : 
 - 否
 - LyricEase 版本号  :
 - 0.9.94.0

**Comment by brandonw3612** [comment]
网络问题请参考[这里](https://brandonw3612.github.io/LyricEase/faq.html). 如果这帮助您解决了问题, 请告知我们.

**Comment by QuickXand** [comment]
> 网络问题请参考[这里](https://brandonw3612.github.io/LyricEase/faq.html). 如果这帮助您解决了问题, 请告知我们.

已经解决了，非常感谢！
