### ISSUE TITLE
关于歌曲列表的问题建议

### ISSUE THREAD

**Issue by kang-u** [brandonw3612/LyricEase#30]
鼠标悬浮歌曲图标的时候出现♥收藏按钮而不是出现▶播放有些反直觉，毕竟收藏一般在听过之后；而且播放按钮距离名称有些远，使用起来有些麻烦。
希望可以修改收藏按钮变为播放按钮
或者添加点击名称播放的功能。

**Comment by brandonw3612** [comment]
使用习惯问题自行适应和调整。
1. 点击逻辑上，我们对鼠标操作使用双击歌曲列表项或鼠标悬浮后点击播放按钮播放，触摸屏设备可单击歌曲列表项播放。我们一直是这么做的，遵照的也是大多数人的习惯，突然改变只怕会让更多人不适应。
2. 按钮对齐的问题，我们在2020年和2021年参考大多数用户的意见，选择对齐排列，是为了让大家在浏览列表时可以减少鼠标移动距离；此前尝试过在歌曲标题后紧靠放置播放按钮，但反馈普遍不好。

另，下面是 Mac / PC 网易云音乐官方客户端的展示逻辑，我们这么设计也是希望大家适应交互体验所需的成本最小化。
<img width="338" alt="Screen Shot 2022-02-16 at 8 00 33 PM" src="https://user-images.githubusercontent.com/29965003/154260575-1c5fe66f-6ec9-4b93-a712-31eb06cf9319.png">
