### ISSUE TITLE
[BUG] 在win10上闪退

### ISSUE THREAD

**Issue by WuJunkai2004** [brandonw3612/LyricEase#32]
## 错误描述
在一台从未安装LyricEase的电脑上安装后，启动时出现`正在初始化数据库`界面，等待一会儿后程序崩溃。闪退，且无报错

## 复现步骤
打开LyricEase。
等待。

## 屏幕截图 / 屏幕录制
反复出现，若需要屏幕录制请[联系我](mailto:wu.junkai@qq.com)

## Windows 和 LyricEase
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎3/‎22
操作系统内部版本	19044.1566
体验	Windows Feature Experience Pack 120.2212.4170.0

处理器	Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz   2.90 GHz
机带 RAM	16.0 GB
设备 ID	D867E9F2-A889-4028-8E74-B5A6D2873D13
产品 ID	00331-10000-00001-AA405
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

LyricEase 版本号  无法打开，应该是20220215 版

**Comment by WuJunkai2004** [comment]
是否由于缺少 x86 的支持库导致？我刚卸载所有 x86 的支持库

**Comment by brandonw3612** [comment]
设备型号是什么呢？可在 Windows 设置 - 系统 - 关于 - 设备规格看到

**Comment by WuJunkai2004** [comment]
> 设备型号是什么呢？可在 Windows 设置 - 系统 - 关于 - 设备规格看到
关于电脑配置的简要信息如下：
.............................................................

CPU  ....... Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 CPUs), ~2.9GHz

主板 ....... 技嘉   H310M S2 2.0

内存 ....... 2 条   16 GB

硬盘 ....... 3 块   ST1000DM003-1CH162 (主)

显卡 ....... NVIDIA GeForce GTX 1050  2 GB

屏幕 ....... HWP3055 1600 x 900 (32 bit) (60 Hz)

网卡 ....... Realtek Gaming GbE Family Controller
