### ISSUE TITLE
“接下来播放” 列表未能完全收起

### ISSUE THREAD

**Issue by AnotiaWang** [brandonw3612/LyricEase#33]
## 错误描述
收起 “正在播放” 界面后，其右侧的 “接下来播放” 列表仍然停留在界面上，遮挡住了其它的元素

## 复现步骤
1. 点击左侧列表的 “心动模式” 按钮
2. 点击下方的 “正在播放” 栏，进入正在播放界面
3. 按 Esc 退出 “正在播放” 界面

## 预期结果
“接下来播放” 列表应当随 “正在播放” 页一起消失

## 屏幕截图
![image](https://user-images.githubusercontent.com/62269186/154948916-3f41da0c-dfc8-4494-a5ed-8dee4398b005.png)

## Windows 和 LyricEase
 - Windows 版本号  : Windows 11 22000.527
 - Windows SKU  : 家庭版
 - 是否为预览体验计划  : 否
 - LyricEase 版本号  : v0.10.103.0

## 附加信息
我是在 “正在播放” 页面进入动画没播放完的时候按了返回，然后就这样了。启动 App 后第一次进入这个界面，右侧列表的动画是从上往下的，大概动画没播放完卡住了，还停留在半路，并且没法让它消失。后来尝试复现了一下没成功，概率挺低的 😂猜测可能和动画有点关系，大佬看看能不能定位到原因……

**Comment by brandonw3612** [comment]
等微软更新相关的UI库吧. 这块处理不了.

**Comment by AnotiaWang** [comment]
好的，谢谢回复
