### ISSUE TITLE
[BUG] 有部分歌曲不显示歌词，仅显示作词作曲以及歌词贡献人

### ISSUE THREAD

**Issue by FinaFina233** [brandonw3612/LyricEase#34]
## 错误描述
有部分歌曲不显示歌词，仅显示作词作曲以及歌词贡献人

## 复现步骤
1. 打开歌曲歌词页面

## 预期结果
正常显示歌词

## 屏幕截图 / 屏幕录制
![COX$%H62M~9U48Z%K9P%6G](https://user-images.githubusercontent.com/52440333/155750050-9be3302a-4057-46c1-a267-2bb553a7c9a7.png)
![DPFK}WRL)JEYZ(EZW)W8BYC](https://user-images.githubusercontent.com/52440333/155750063-57c1026e-419a-48a1-a3a4-4784e19c4ab9.png)
![UK05_(CH1V~D9}5SR6$4F58](https://user-images.githubusercontent.com/52440333/155750071-b18d6905-3b0c-4a29-a7fd-8f96f2baf9d3.png)

## Windows 和 LyricEase
 - Windows 版本号: [Windows 11 22000.527]
 - Windows SKU: [专业版]
 - 是否为预览体验计划: [是]
 - LyricEase 版本号: 0.10.103（多个版本都有出现，推测非版本问题）

## 附加信息
此情况会在同一个艺人的不同歌曲上多次出现。

**Comment by brandonw3612** [comment]
请提供歌曲ID.

**Comment by FinaFina233** [comment]
我没有收到这个邮件，我从来不会收到邮件233.

**Comment by FinaFina233** [comment]
歌曲id：1914587484、1908833793、1900195395

**Comment by FinaFina233** [comment]
any clues

**Comment by brandonw3612** [comment]
LRC 格式解析问题。此前默认加载 `[00:00.000]` 格式的时间戳，而不加载形如 `[00:00:000]` 的时间戳。
下一版本修复
<img width="1920" alt="Screenshot 2022-02-28 142227" src="https://user-images.githubusercontent.com/29965003/155934626-65febe9c-bf37-4d47-8110-edd71ff6eedf.png">

**Comment by FinaFina233** [comment]
原来是这样，辛苦了。谢谢

**Comment by FinaFina233** [comment]
啊这，不好意思，我不知道关闭问题会移到Done里去

**Comment by brandonw3612** [comment]
0.10.104 已完成
