### ISSUE TITLE
[BUG] 无法联网

### ISSUE THREAD

**Issue by citydirector** [brandonw3612/LyricEase#36]
## 错误描述
![image](https://user-images.githubusercontent.com/45933075/156164257-d9c5d9e3-b87e-45d9-ad32-1dd149230da9.png)

## 复现步骤
仅初始安装

## Windows 和 LyricEase
 - Windows 版本号 Windows 11 22563.1
 - Windows SKU 专业工作站版
 - 是否为预览体验计划 是
 - LyricEase 版本号 latest

## 备注
网易云客户端和music.163.com都能正常工作

**Comment by brandonw3612** [comment]
https://brandonw3612.github.io/LyricEase/faq.html
已参考？

**Comment by citydirector** [comment]
哇，回复好快（惊喜
确实，参考过了

**Comment by brandonw3612** [comment]
DNS 恢复默认，代理关闭后不存在这类情况才对啊.
如果还解决不了那就只能还原网络设置或者重启试试了.
我这边几台设备都是正常的，不是API的锅.

**Comment by brandonw3612** [comment]
> 第二条“选择能够使用你的WLAN数据的应用”我找不到在哪里，不过我想其他UWP应用都能正常联网，问题应该不会出在那里

这个选项仅部分系统会出现. 很多UWP的网络权限被默认关闭了. 找不到也是正常的, 找不到的时候就是默认开启.

**Comment by citydirector** [comment]
> DNS 恢复默认，代理关闭后不存在这类情况才对啊. 如果还解决不了那就只能还原网络设置或者重启试试了. 我这边几台设备都是正常的，不是API的锅.

我尝试过“重置网络”选项，但除了需要我重新输入一遍超级长的wifi密码以外，似乎并没有效果（

**Comment by brandonw3612** [comment]
明早更新一下软件再看看吧. 分析了一下网络那边的问题, 做了一个小改动, 一会儿推一个小更新.

**Comment by citydirector** [comment]
很奇怪呢，网易云的客户端是正常的，网页也是正常的，然后其他UWP应用(比如QQ音乐UWP版，还有Windows自带的应用)都能正常联网

**Comment by citydirector** [comment]
啊，还是不行（

（差点忘了这茬）

**Comment by citydirector** [comment]
发现一个怪异现象
我用火绒开启程序联网控制，这时所有程序需要联网都需要手动同意；然后我从应用商店安装了杜比，弹了联网请求，新安装的QQ音乐UWP也弹了，但LyricEase就没有弹，然后我检查过了火绒的联网控制列表，也没有LyricEase的记录

**Comment by brandonw3612** [comment]
卸载重装一下试试看呢？或者打开后在登录页的设置里把代理设置为关闭看看？

**Comment by citydirector** [comment]
> 卸载重装一下试试看呢？或者打开后在登录页的设置里把代理设置为关闭看看？

尝试过在应用商店里重装或者msix安装包重装，系统网络自动配置代理那里试过"关闭"或者"自动"，下面两个均为关闭状态

**Comment by brandonw3612** [comment]
我指的是 LyricEase 在0.10.106版本中支持软件内设置代理。在登录页的设置按钮中有代理设置。

**Comment by citydirector** [comment]
> 我指的是 LyricEase 在0.10.106版本中支持软件内设置代理。在登录页的设置按钮中有代理设置。

我在软件内配置了代理127.0.0.1:10808（v2rayN的本地监听端口）测试了一下，v2rayN那边有日志输出（截图）
![image](https://user-images.githubusercontent.com/45933075/156931395-cca30559-cca5-40e8-9543-a1ac7ee15828.png)

**Comment by brandonw3612** [comment]
uwp软件内代理没用，用系统代理试试。
需要软件内开启代理 + 系统设置启用代理。

**Comment by citydirector** [comment]
> uwp软件内自定义代理没用，用系统代理试试。 需要软件内开启代理 + 系统设置启用代理。

v2rayN挂了全局，软件内设置了使用系统代理，第一次成功刷出了登录二维码

**Comment by citydirector** [comment]
> v2rayN挂了全局，软件内设置了使用系统代理，第一次成功刷出了登录二维码

emm，得一直挂着代理，没有代理就断网，真见鬼

**Comment by brandonw3612** [comment]
系统关闭代理，在软件内设置同时关闭不可以联网吗

**Comment by citydirector** [comment]
> 系统关闭代理，在软件内设置同时关闭不可以联网吗

不可以，只能走代理才可以联网

**Comment by brandonw3612** [comment]
应该还是系统环境设置的问题了。0.10.106我们重新检查了网络部分的代码，单就软件这边是不会连不上网的。再就是开代理可以联网应该也表明不是软件内部的原因了。这边 issue 暂时先关闭。

**Comment by citydirector** [comment]
> 应该还是系统环境设置的问题了。0.10.106我们重新检查了网络部分的代码，单就软件这边是不会连不上网的。再就是开代理可以联网应该也表明不是软件内部的原因了。这边 issue 暂时先关闭。

嗯嗯
我刚刚尝试了解除UWP应用网络隔离，也不管用

**Comment by citydirector** [comment]
淦，找到问题了（

我检查了我的路由器，发现家里这台路由器的“解锁网易云灰色歌曲”插件(Go版本)是开着的，关掉就正常了

**Comment by kengwang** [comment]
顺带说下这个问题，这是因为网易云解灰是没有 HTTPS 证书的所以导致 HTTPS 请求证书校验失败而无法访问。
网易云音乐客户端会自动降级到 HTTP 而 .NET 相关库不会
