### ISSUE TITLE
[BUG] 无法将任何歌曲添加到自己的任何歌单

### ISSUE THREAD

**Issue by Revincx** [brandonw3612/LyricEase#37]
## 错误描述

无法将任何歌曲添加到自己的歌单，报错："歌曲添加到歌单失败"。
确认歌单里不存在相同的音乐。
从歌单删除歌曲没有问题。

## 复现步骤

不知道怎么复现，就是右键歌曲 -> 添加到歌单

## 预期结果

成功添加到歌单

## 屏幕截图 / 屏幕录制

![image](https://user-images.githubusercontent.com/25524750/156917717-7bfd1896-1e9d-469b-82ba-1f9d5000843b.png)

## Windows 和 LyricEase
 - Windows 版本号  : Windows 10 19044.1466
 - Windows SKU  : 专业版
 - 是否为预览体验计划  : 否
 - LyricEase 版本号  : 0.10.106

## 附加信息

上一个版本也有这个问题

**Comment by brandonw3612** [comment]
已知问题，全局添加到歌单失效。
0.11修复。

**Comment by StillOpen** [comment]
![image](https://user-images.githubusercontent.com/45067868/160132958-23cef4b7-13b9-4dc0-9f51-bedd06ddd8fa.png)
请问一下，0.11版本大概什么时候会释放出来呢？LyricEase重度使用者表示，歌曲收藏功能真的很重要Q A Q。

**Comment by brandonw3612** [comment]
> ![image](https://user-images.githubusercontent.com/45067868/160132958-23cef4b7-13b9-4dc0-9f51-bedd06ddd8fa.png)
> 请问一下，0.11版本大概什么时候会释放出来呢？LyricEase重度使用者表示，歌曲收藏功能真的很重要Q A Q。

已经有一个版本在等商店审核了。等微软。这次不知道为什么审核有点慢。

**Comment by brandonw3612** [comment]
v0.11.114 已修复。

**Comment by liyize419** [comment]
希望加入导入外部音乐的功能
