### ISSUE TITLE
[FEATURE] 点×最小化而不是退出

### ISSUE THREAD

**Issue by phyzhenli** [brandonw3612/LyricEase#39]
## 类似于很多APP点击×自动最小化的效果。

![image](https://user-images.githubusercontent.com/48823046/157787398-7b0e8dee-6d4c-4440-af32-9f592c37ecc4.png)

**Comment by brandonw3612** [comment]
这些App里头有UWP吗

**Comment by brandonw3612** [comment]
Dup of #20
