### ISSUE TITLE
[BUG] 搜索在特定场景下重复显示结果

### ISSUE THREAD

**Issue by QuickXand** [brandonw3612/LyricEase#4]
## 错误描述

搜索结果列表中出现多个重复项目

## 复现步骤

在搜索界面输入用户名，在结果加载完成之前多次点击用户选项卡，即可复现。

结果如图。

## 屏幕截图 / 屏幕录制

![image](https://user-images.githubusercontent.com/96399652/146947383-ce7eb232-3016-4510-859a-981566e364d2.png)

## Windows 和 LyricEase
 - Windows 版本号  :
 - windows 11 22000.376
 - Windows SKU  :
 - 家庭版
 - 是否为预览体验计划  : 
 - 否
 - LyricEase 版本号  :
 - 0.9.94.0

**Comment by brandonw3612** [comment]
我们已收到并将在1月调查修复.
PS: 后期反馈麻烦把标题填一下.
