### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by bluexie** [brandonw3612/LyricEase#40]
## 错误描述
打不开，显示一下然后就退出了

windows 10 专业版 20H2 
操作系统版本 19042.572

**Comment by brandonw3612** [comment]
是否已参考 [FAQ](https://brandonw3612.github.io/LyricEase/faq.html) 中《系统和软件依赖》部分的提示？

**Comment by brandonw3612** [comment]
请提供设备型号。
具体操作方式：按下 Windows+R 组合键，输入 msinfo32，在弹出的对话框中找到 系统型号 (System Model) 所对应的值。

**Comment by bluexie** [comment]
正在尝试FAQ中的《系统和软件依赖》部分的提示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "brandonw3612/LyricEase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [brandonw3612/LyricEase] 闪退 (Issue #40)





 
请提供设备型号。
 具体操作方式：按下 Windows+R 组合键，输入 msinfo32，在弹出的对话框中找到 系统型号 (System Model) 所对应的值。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bluexie** [comment]
您好，具体情况如gif所示，启动之后闪退
由于邮件中无法添加过大的gif文件，请参考阿里云盘分享的链接
https://www.aliyundrive.com/s/LcXLyqkVY5E

应用程序在图片中的页面闪退
感谢帮助












------------------ 原始邮件 ------------------
发件人:                                                                                                                        "brandonw3612/LyricEase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [brandonw3612/LyricEase] 闪退 (Issue #40)





 
请提供设备型号。
 具体操作方式：按下 Windows+R 组合键，输入 msinfo32，在弹出的对话框中找到 系统型号 (System Model) 所对应的值。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brandonw3612** [comment]
系统安装渠道是？是否为微软官方镜像？FAQ里的提示是否都已检查？
目前我们在所有应用崩溃记录中没有发现任何与您描述相符的报告。请按上述评论中描述的方法提供您的设备型号。

**Comment by bluexie** [comment]
> 系统安装渠道是？是否为微软官方镜像？FAQ里的提示是否都已检查？ 目前我们在所有应用崩溃记录中没有发现任何与您描述相符的报告。请按上述评论中描述的方法提供您的设备型号。
系统镜像不是微软的官方镜像，设备型号之前已回复，似乎消失了，抱歉，重新提供如下。
![image](https://user-images.githubusercontent.com/59362200/157864521-aefea21c-02fe-4eb0-9d2b-f9c49ed0259e.png)
系统型号：81FU
FAQ中的提示已经尝试，软件从官方商店中下载，appx文件不会获取所以通过官方渠道获取，但是scf /scannow检查需要先重启，稍等尝试

**Comment by brandonw3612** [comment]
镜像非官方会非常麻烦，很多第三方平台推出所谓“精简版/纯净版” Windows 系统，删减的内容中是存在 LyricEase 运行必需的组件的。 sfc命令会提示系统文件收到修改的部分。为安全和稳定起见，请勿使用第三方 Windows 镜像。

**Comment by bluexie** [comment]
> 镜像非官方会非常麻烦，很多第三方平台推出所谓“精简版/纯净版” Windows 系统，删减的内容中是存在 LyricEase 运行必需的组件的。 sfc命令会提示系统文件受到修改的部分。为安全和稳定起见，请勿使用第三方 Windows 镜像。

多谢提醒 。sfc 命令已经检查完毕，显示 未找到完整性冲突
![image](https://user-images.githubusercontent.com/59362200/157867992-e6e315cc-0e17-4c71-84a0-3cba3b8717b2.png)
第三方系统确实容易出错，等之后重装系统再说，多谢帮助

**Comment by brandonw3612** [comment]
此 issue 暂时关闭
