### ISSUE TITLE
[FEATURE] 使用本地代理但没有启用 Loopback 时提供更好的提示

### ISSUE THREAD

**Issue by shirok1** [brandonw3612/LyricEase#41]
## 你的建议
前几个版本有设置本地代理的时候直接闪退的问题，没有给出任何提示，后面我才想起来 UWP 有 Loopback 限制这么个东西。

## 该建议的实现方式
检测到网络故障的时候检测代理服务器是否为本地，如果是给出具体解决方法，比如可以一键复制的 PowerShell 指令。

**Comment by brandonw3612** [comment]
v0.11.114 已改善。
<img width="478" alt="Screen Shot 2022-03-28 at 12 53 37" src="https://user-images.githubusercontent.com/29965003/160328893-67e31000-723f-40a5-9512-9d949a4a92b2.png">
