### ISSUE TITLE
[FEATURE] 希望增加全局快捷键

### ISSUE THREAD

**Issue by ssxwcz** [brandonw3612/LyricEase#42]
## 你的建议

您好，希望能够支持全局快捷键功能，实现音乐暂停、切换

## 该建议的实现方式

![image](https://user-images.githubusercontent.com/43665491/157998917-1512ec11-7d8d-497c-aa52-fad87d2142b8.png)

**Comment by brandonw3612** [comment]
UWP 体系不支持全局快捷键，目前已支持应用内快捷键。

**Comment by ssxwcz** [comment]
> UWP 体系不支持全局快捷键，目前已支持应用内快捷键。

好吧，很遗憾了

**Comment by alex3236** [comment]
### 提供一个解决方案
使用 [PowerToys](https://github.com/microsoft/PowerToys) 的 `键盘管理器` 功能。

![image](https://user-images.githubusercontent.com/45303195/162678871-7da8e951-15ea-4086-b095-e38c8fad7c19.png)

如图所示，将需要的全局快捷键映射到媒体键。对应如下：

| 媒体键 | 功能 |
| - | - |
| Play | 播放 |
| Pause | 暂停 |
| Play/Pause Media | 播放或暂停 |
| Previous Track | 上一首 |
| Next Track | 下一首 |

**Comment by ssxwcz** [comment]
> ### 提供一个解决方案
> 使用 [PowerToys](https://github.com/microsoft/PowerToys) 的 `键盘管理器` 功能。
> 
> ![image](https://user-images.githubusercontent.com/45303195/162678871-7da8e951-15ea-4086-b095-e38c8fad7c19.png)
> 
> 如图所示，将需要的全局快捷键映射到媒体键。对应如下：
> 
> 媒体键	功能
> Play	播放
> Pause	暂停
> Play/Pause Media	播放或暂停
> Previous Track	上一首
> Next Track	下一首

这个方案可行，多谢！
