### ISSUE TITLE
[FEATURE] 支持更换字体

### ISSUE THREAD

**Issue by the1812** [brandonw3612/LyricEase#45]
## 你的建议

希望能够在设置 - 外观中设置整个应用的字体, 因为当语言是中文时默认会使用微软雅黑, 渲染效果很糟糕.

和其他一些应用的对比: (字体为 Sarasa UI SC)

系统设置
![image](https://user-images.githubusercontent.com/26504152/158108075-15cc2d53-7c74-40e7-8f9a-32b6061be044.png)

YesPlayMusic
![image](https://user-images.githubusercontent.com/26504152/158108012-f39f7545-4a27-4491-a75f-400416922786.png)

**Comment by brandonw3612** [comment]
UWP体系内无法使用外部字体文件用于UI显示，我们也没有内置额外字体的计划。
如需替换字体，请自行替换系统显示字体。

**Comment by the1812** [comment]
选择系统中已安装的字体也不行吗, 应该不需要做字体内嵌的

**Comment by brandonw3612** [comment]
调取系统方面研究一下。如果计划调整的话会 reopen。
