### ISSUE TITLE
[BUG] 无法将歌曲添加到歌单

### ISSUE THREAD

**Issue by SaltFi-sh** [brandonw3612/LyricEase#47]
## 错误描述

当我尝试把歌曲添加到歌单的时候，会提示我 歌曲添加到歌单失败

## 复现步骤

1. 选择一个歌曲点击更多中的添加到歌单
2. 提示添加失败
## 预期结果

能够正常的添加到歌单
## 设备, Windows 和 LyricEase
 - 设备型号 Surface pro 8
 - Windows 版本号 Windows11 22000.556
 - Windows SKU  家庭版 
 - 是否为预览体验计划  否 :
 - LyricEase 版本号 0.10.106

**Comment by brandonw3612** [comment]
能否看看其他人提过的 issue ?

**Comment by brandonw3612** [comment]
Dup of #37 .
