### ISSUE TITLE
[BUG] 右键任务栏图标 点击我喜欢的音乐 出现“参数错误”

### ISSUE THREAD

**Issue by U98de** [brandonw3612/LyricEase#48]
## 错误描述

将LyricEase固定到任务栏，关闭软件后，右键，点击我喜欢的音乐，出现参数错误的提示框
## 复现步骤

1. 将LyricEase固定到任务栏
2. 在LyricEase关闭状态下右键任务栏图标
3. 选择“我喜欢的音乐”
4. 错误以弹出提示框的形式呈现
## 预期结果

直接转到我喜欢的音乐
## 屏幕截图 / 屏幕录制
![LE 00_00_00-00_00_30](https://user-images.githubusercontent.com/91559690/159444724-cb45e3cd-cdc7-4ecc-b280-1892d0dbe0cb.gif)

## 设备, Windows 和 LyricEase
 - 设备型号  :系统型号	ASUS TUF Gaming A15 FA506IV_FA506IV
 - Windows 版本号  :Windows 11 专业版 10.0.22000.588.0
 - Windows SKU  :专业版
 - 是否为预览体验计划  : 是
 - LyricEase 版本号  :0.10.106

## 附加信息

点击“搜索”和“账户”正常，且仅在关闭状态下点击“我喜欢的音乐”会出现问题

**Comment by brandonw3612** [comment]
已知问题，一直忘了修复。感谢反馈。我们将在 0.11.x 中修复该问题。

**Comment by brandonw3612** [comment]
v0.11.114 已修复。

**Comment by U98de** [comment]
v0.11.114 还是有这个bug

**Comment by U98de** [comment]
有时还是会出现这个bug，印象中出现过一次，刚刚又出现了一次，但是每次清除缓存数据后就能解决。不知道如何复现（个人猜测是因为版本更新的问题

**Comment by brandonw3612** [comment]
下版本将彻底解决这一问题。这块的代码已完成修改和测试。

**Comment by brandonw3612** [comment]
`v0.11.118` 已彻底修复。
