### ISSUE TITLE
[FEATURE]最小化应用后,使用快捷键

### ISSUE THREAD

**Issue by CnsMaple** [brandonw3612/LyricEase#50]
# 问题:
现在应用最小化后,无法使用快捷键,例如:上一首歌,下一首歌等快捷键.
# 需求:
希望可以在最小化应用后仍然可以使用快捷键.

**Comment by kengwang** [comment]
Dup #42
Please refer: https://github.com/brandonw3612/LyricEase/issues/42#issuecomment-1065786276
