### ISSUE TITLE
[BUG] 某些情况下热词无法正常显示翻译

### ISSUE THREAD

**Issue by zhanghua000** [brandonw3612/LyricEase#53]
## 错误描述

热词设置为第二行显示翻译，但在播放带翻译的歌曲时偶发性不能正常显示

## 复现步骤

程序设置通过热词提供桌面歌词
热词设置双行显示下一行歌词或者翻译
播放歌词带翻译的外文歌曲

## 预期结果

热词偶尔不能正常显示翻译，如截图所示
主要在歌的第一句歌词或者较长伴奏之后会出现，但出现机会不多，一首歌大约有一次出现。

## 屏幕截图 / 屏幕录制

![image](https://user-images.githubusercontent.com/17194552/160360660-297cd8ad-8745-41a7-a479-b42f6418cffe.png)

## 设备, Windows 和 LyricEase
 - 设备型号  : Dell G7 7588
 - Windows 版本号  : Win11 10.0.22581
 - Windows SKU  : 专业工作站版
 - 是否为预览体验计划  :  是
 - LyricEase 版本号  : 0.11.114

## 附加信息

在出现问题之后暂停一会儿再继续播放似乎就可以正常显示翻译了，但之后仍有出现这个问题的机率

**Comment by zhanghua000** [comment]
经使用 HyPlayer 测试发现也有类似问题，似乎是热词的缺陷，抱歉

**Comment by brandonw3612** [comment]
@cnbluefire

**Comment by cnbluefire** [comment]
麻烦提供一下出问题的歌曲链接

**Comment by zhanghua000** [comment]
https://music.163.com/#/song?id=1499826814
这个是截图里面的歌曲链接，但在我这里所有带翻译的歌曲都有出现这个问题

**Comment by cnbluefire** [comment]
如果播放过程中出现翻译了，那说明解析是没问题的。

出现这个现象的原因在于网易云是将翻译作为一个单独的lrc文件提供的，热词并没有像其他软件一样将翻译与歌词本身进行整合，而是作为两个歌词同时播放的。由于歌词和翻译本身的时间戳不一致，就可能出现这个现象。

因为整合歌词和翻译还会带来其他问题，短期内热词不会提供这个功能。

**Comment by zhanghua000** [comment]
啊好的，感谢解答。
不过这个问题似乎只会影响一句歌词。比如，尽管截图那一句有问题，但它之后的那一句翻译和原文看起来是正常的。在出现问题的这一句播放过程中用热词的播放控制暂停然后恢复的话这一句的翻译也会马上正常出现了。所以其实我怀疑是不是真的是由于两个歌词时间戳不同步的原因导致的

**Comment by cnbluefire** [comment]
抱歉，刚刚检查了下逻辑，确实有一些错误可能会导致漏句，后续会修复
