### ISSUE TITLE
[BUG] 链接蓝牙耳机之后点击播放，只有几秒钟有声音

### ISSUE THREAD

**Issue by LWZYFFW** [brandonw3612/LyricEase#54]
## 错误描述

 链接蓝牙耳机之后点击播放，只有几秒钟有声音
三星buds pro，hands free AG audio 模式

放大音量不行；
点击暂停，再次点击播放，又会播放几秒钟

## 设备, Windows 和 LyricEase
 - 设备型号  :
 - Windows 版本号  :
 - Windows SKU  :
 - 是否为预览体验计划  : 
 - LyricEase 版本号  :

**Comment by brandonw3612** [comment]
Hands Free 模式下音频播放挺多问题的。有尝试 Stereo 模式吗？

**Comment by brandonw3612** [comment]
看描述像是系统和耳机连接性的问题。此前我们收到的反馈基本也是在解决系统问题后就正常了。

**Comment by LWZYFFW** [comment]
> Hands Free 模式下音频播放挺多问题的。有尝试 Stereo 模式吗？

 Stereo 模式 没问题

**Comment by brandonw3612** [comment]
极可能是系统管理方面的问题, 对 Hands Free 类型的音频设备自动节能一类. 所以我们无法在软件层面调整. 可以研究下系统设置, 例如是在设备管理器中查看能源使用相关的选项.
