### ISSUE TITLE
后台播放音乐会蓝屏

### ISSUE THREAD

**Issue by liyize419** [brandonw3612/LyricEase#55]
玩csgo后台播放音乐，会蓝屏

电脑配置
![QQ截图20220330154918](https://user-images.githubusercontent.com/102503368/160779772-d128d193-caf9-41e3-8fc1-da11f9babd0f.png)

**Comment by liyize419** [comment]
![QQ截图20220330155056](https://user-images.githubusercontent.com/102503368/160780039-f724379b-a2f7-4b46-962c-96e2785947d4.png)
d'n系统版本

**Comment by brandonw3612** [comment]
蓝屏问题在系统层次. 优先排查系统配置、驱动版本、游戏兼容性等问题. 蓝屏时提示的信息是什么? 另, 游戏和 LyricEase 分别独立运行时会蓝屏吗?

**Comment by liyize419** [comment]
游戏运行时单独运行不会 音乐单独运行时不会 一起运行时会

**Comment by liyize419** [comment]
应该是我电脑配置问题
![QQ图片20220330163336](https://user-images.githubusercontent.com/102503368/160788139-e9786e86-a336-4631-97a6-f7ab4e7698ea.png)
这样就不会蓝屏了

**Comment by brandonw3612** [comment]
好的, 那这边 issue 关闭了.
