### ISSUE TITLE
[BUG] 歌名过长问题

### ISSUE THREAD

**Issue by CnsMaple** [brandonw3612/LyricEase#56]
## 错误描述
歌名长的歌曲,会出现重叠问题

## 复现步骤
直接播放歌名长的歌曲

## 预期结果
不同的文字应该放在正确的地方

## 屏幕截图 / 屏幕录制
例如:图片中间上面的位置
<img width="1120" alt="1ebcf20484476be6732ed1671a6dd58" src="https://user-images.githubusercontent.com/92523839/160998315-667af073-1903-44c2-b71d-5cda604e91f9.png">

## 设备, Windows 和 LyricEase
 - 设备型号  :
 - Windows 版本号  :win10
 - Windows SKU  :家庭版
 - 是否为预览体验计划  : 
 - LyricEase 版本号  :0.11.114

**Comment by CnsMaple** [comment]
# 出现的情况:
并不是每次播放都有这样的情况,偶尔会有,软件重启就解决了

**Comment by brandonw3612** [comment]
这种情况调整窗口大小就会恢复
