### ISSUE TITLE
win10 21H1 19043.1415 打开后闪退

### ISSUE THREAD

**Issue by uioz** [brandonw3612/LyricEase#6]
## 错误描述
登陆界面已经展示, 无法进行UI交互, 数秒后闪退.

## 复现步骤
点击启动后随即闪退

## 预期结果
正常运行

## 屏幕截图 / 屏幕录制
![动画](https://user-images.githubusercontent.com/36815772/147523823-5c70db3d-339a-4a85-a954-e4edf4544ad8.gif)

## Windows 和 LyricEase
 - Windows 版本号 win10 19043.1415
 - Windows SKU 专业版
 - 是否为预览体验计划 否
 - LyricEase 版本号 0.9.94

**Comment by brandonw3612** [comment]
我们已收到问题. 下面需要您提供以下信息:
1. 您是否尝试过重置/重新安装应用?
2. 您是否使用过以前版本的LyricEase? 如果答案是肯定的, 先前版本中是否存在此问题?
3. 您设备上的Windows系统安装渠道是否为Microsoft官方或可信任的原版Windows镜像? 据我们了解, 使用部分第三方Windows系统, 尤其是网络流传"精简版"Windows系统会出现我们无法修复的问题.

**Comment by uioz** [comment]
1. 尝试过，但是没有效果
2. 之前安装过，但是是很久以前的事情了，之前安装的时候有没有问题我忘记了
3. windows 原版镜像并非修改版

本来我是想看下日志的，结果没找到软件安装的目录，要有的话可能比较容易定位问题。

**Comment by brandonw3612** [comment]
可以参考此博客 https://cloud.tencent.com/developer/article/1402653 描述的方法抓取崩溃后生成的 dump 文件并和我们共享.

另, 我们在合作伙伴中心查看了相关崩溃的记录, 目前可定位到的问题来自跳转列表, 发生概率极低. 我们会尝试修复此问题. 如有其他信息请与我们联系.

**Comment by uioz** [comment]
[LyricEase.Core.exe.32876.zip](https://github.com/brandonw3612/LyricEase/files/7791685/LyricEase.Core.exe.32876.zip)

**Comment by brandonw3612** [comment]
您好，这两天我们仍在研究该问题。请问您的设备上安装的 Windows 系统架构是哪一个？我们在 MacBook (M1 Pro) 虚拟机内也发现了类似问题，想与您确认一下。

**Comment by brandonw3612** [comment]
不好意思，我们看到了是x64，忽略了dmp文件的一些信息。
