### ISSUE TITLE
[FEATURE] UI上的小建议

### ISSUE THREAD

**Issue by haloaxu** [brandonw3612/LyricEase#61]
## 你的建议

边距不一致看起来不是很和谐
![image](https://user-images.githubusercontent.com/52599960/161684595-c03cc8c6-b3a1-4ae5-b880-f31be246444c.png)

## 该建议的实现方式
 
往里缩和下方的功能键对齐
![image](https://user-images.githubusercontent.com/52599960/161685391-582deafc-086c-4c44-a4f4-e3a2599fd26b.png)

## 附加信息

win11  15寸  1080P  I79750H  0.11.116

**Comment by brandonw3612** [comment]
宽屏逻辑不允许。
现在顶部是贴边，下方是居中。
不过后面会微调一下逻辑。
<img width="1800" alt="Screen Shot 2022-04-05 at 16 34 19" src="https://user-images.githubusercontent.com/29965003/161713387-89cb0691-a158-4973-aff9-4f697c7be831.png">
