### ISSUE TITLE
建议加上一个代理服务器填写端口

### ISSUE THREAD

**Issue by KimTson** [brandonw3612/LyricEase#62]
由于网易云版权太少，希望作者大大看看能否加上网易云的代理端口设置，让用户可以自定义代理设置

**Comment by brandonw3612** [comment]
UWP 不能使用自定义代理，只可以走系统代理。
如果非要单独设置，自己去找辅助工具。用代理的时候记得 Loopback。

**Comment by KimTson** [comment]
好的，多谢，不能自定义代理还是有点遗憾，但总的来说您这款第三方网易云的使用体验还是十分不错的😀

Brandon Wong ***@***.***> 于2022年4月6日周三 14:57写道：

**Comment by brandonw3612** [comment]
可参考 https://zhuanlan.zhihu.com/p/128965700

**Comment by KimTson** [comment]
好的，已了解，多谢

Brandon Wong ***@***.***> 于2022年4月6日周三 15:07写道：
