### ISSUE TITLE
[BUG] 歌词界面GPU占用过高

### ISSUE THREAD

**Issue by Fkst5in** [brandonw3612/LyricEase#63]
## 错误描述
音乐播放界面（歌词滚动显示时）GPU占用过高，界面卡顿

## 复现步骤
播放任意歌曲，打开播放界面，显示滚动歌词

## 预期结果
合理的GPU占用，界面流畅

## 屏幕截图 / 屏幕录制
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/33352000/162016520-b17b6442-ba99-42fa-b385-35b66b25ee4e.png">

## 设备, Windows 和 LyricEase
 - 设备型号 ROG Zephyrus M16【幻16】 :
 - Windows 版本号  10.0.22000 :
 - Windows SKU 专业工作站版 :
 - 是否为预览体验计划 否  : 
 - LyricEase 版本号  0.11.116  :

## 附加信息
用的是12900H的核心显卡，新装的系统。经过测试，在上述情况下，dwm.exe的GPU占用将达到100%，关闭LyricEase后恢复正常

**Comment by brandonw3612** [comment]
优先自行排查核显驱动、用户设置、系统调度、设备兼容性等问题。
我们在8代、9代、10代、11代酷睿移动端设备上测试均无卡顿，在效果全开的时候 GPU 占用高属于正常现象，0.11的下一次更新我们会优化一些动画的性能，但针对特定设备的异常我们无法解决。对于UWP这类通用应用，同样也不存在专门为某一型号的硬件设备优化的方法。
