### ISSUE TITLE
[BUG] 无法正常播放音乐

### ISSUE THREAD

**Issue by WhatDamon** [brandonw3612/LyricEase#65]
## 错误描述

播放音乐会发出刺耳声音并且越来越大覆盖音乐，然后就啥也听不到了，测试后发现所有方式播放都有，重置软件无效，其他使用同样API的第三方网易云客户端没有此问题
## 复现步骤

1. 打开**任意音乐**（从个人**测试结果**总结）
## 预期结果

播放音乐同时发出刺耳声音，刺耳声音会在几秒中覆盖音乐，然后再过一会就什么也听不见了，暂停后继续再次重复此问题
## 屏幕截图 / 屏幕录制

https://user-images.githubusercontent.com/59256766/162586422-b4b40efd-710b-43d5-97b6-03a9891b2e98.mp4

## 设备, Windows 和 LyricEase
 - 设备型号  : MacBookPro8,2(**MacBook Pro 2011年初版，15寸**)
 - Windows 版本号  : Windows 11 Insider Preview **Dev 22593.1** ni_release
 - Windows SKU  : 专业版
 - 是否为预览体验计划  : 是
 - LyricEase 版本号  : v0.11.116(20220402)

## 附加信息

此问题在Build 22581中也存在，并且软件旧版没有此问题，初步判断不是系统问题（预览版每次更新约等于保留用户所有数据重装系统，原则上就是运行了SFC检查），从Microsoft Store下载，应该不存在丢失依赖项，并且设置软件，重置软件依旧存在此问题，可能时硬件原因导致，我也没有其他可用的播放设备，因此先报告此BUG
_顺便给条思路，仅供参考：检查播放模块是否存在某些不合理代码（如屎山代码），如果是我的硬件问题可以做一些高级自定义选项（如调音功能，目前可以自定义的功能太少了）_

**Comment by WhatDamon** [comment]
我的电脑扬声器可能不太好，但是不会有刺耳声音，最多也就爆破音，，，，，，

**Comment by brandonw3612** [comment]
1. 此硬件设备不满足 Windows 11 安装的最低要求，建议尝试安装 Windows 10 且在各设备驱动正常的情况下使用；
2. 音频播放和网络通信层次的 API 没有任何关系，和其他软件表现不同是因为音频播放核心选用不同，我们采用的是基于 XAudio2 的 AudioGraph，该核心与设备的兼容问题我们不提供解决方案；
3. 不会针对任何特殊硬件单独排查或适配，我们在播放核心中也没有权限调整具体设备的配置。
