### ISSUE TITLE
[FEATURE]因歌曲问题无法正常播放时取消弹窗报错

### ISSUE THREAD

**Issue by tangqiu0205** [brandonw3612/LyricEase#66]
## 错误描述
 歌曲可以正常播放, 但是会提示这个错误.

## 复现步骤
  后台让它播放几首歌曲, 就会出现提示.

## 屏幕截图 / 屏幕录制
<img width="414" alt="image" src="https://user-images.githubusercontent.com/37826977/162605947-5e31ac6a-72e5-47c1-91eb-31e1e73d5eaf.png">

## 设备, Windows 和 LyricEase
 - 设备型号  :LAPTOP-1L0799RG
 - Windows 版本号  : windows 11   22000.593
 - Windows SKU  :
 - 是否为预览体验计划  : 
 - LyricEase 版本号  : 0.11.116

**Comment by brandonw3612** [comment]
弹这个对话框说明有歌曲音频存在问题，然后就自动跳过到下一首了。
哪儿有问题吗？

**Comment by ZhangHu1225** [comment]
无法播放其实不用报这个错误, 这样会被误以为程序出现异常了.

**Comment by brandonw3612** [comment]
想想也是，下次调整一下

**Comment by brandonw3612** [comment]
这边归入功能建议了，不算 bug

**Comment by brandonw3612** [comment]
`0.11.118` 已作出调整。
