### ISSUE TITLE
[FEATURE] 对齐播放页面元素

### ISSUE THREAD

**Issue by alex3236** [brandonw3612/LyricEase#67]
## 你的建议

将左右上角的按钮与底部按钮对齐。
![image](https://user-images.githubusercontent.com/45303195/162618928-cf962417-22a8-4050-becc-22a9145a4923.png)

**Comment by brandonw3612** [comment]
Dup of #61
看下现存 issue 求求了

**Comment by alex3236** [comment]
> Dup of #61 看下现存 issue 求求了

搜索对齐没搜到啊 :cry: 五十几个 Issue 总不能一个个看吧

**Comment by brandonw3612** [comment]
行
