### ISSUE TITLE
[BUG] 收藏页面，个人主页无法打开

### ISSUE THREAD

**Issue by cirenwuming** [brandonw3612/LyricEase#68]
## 设备, Windows 和 LyricEase
 - 设备型号  :
 - Windows 版本号  :
 - Windows SKU  :
 - 是否为预览体验计划  : 
 - LyricEase 版本号  :

## 附加信息

点击左下方用户名跳转到个人主页显示“加载页面时遇到问题”
![}0GY0_0LX3HCET2R2VVN~TG](https://user-images.githubusercontent.com/63985065/162738931-18f14c5b-64b4-4071-b625-6e3562369e4f.png)

**Comment by cirenwuming** [comment]
设备型号 :戴尔灵越5580
Windows 版本号 :10
Windows SKU :19043（21H1）
是否为预览体验计划 :否
LyricEase 版本号 :0.11.116

**Comment by cirenwuming** [comment]
510400957




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Brandon ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 晚上8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [brandonw3612/LyricEase] [BUG] 收藏页面，个人主页无法打开 (Issue #68)





 
提供一下用户id

**Comment by cirenwuming** [comment]
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Brandon ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 晚上10:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [brandonw3612/LyricEase] [BUG] 收藏页面，个人主页无法打开 (Issue #68)





 
排查完成，下一版修复此问题。
 对于目前版本，在移动版客户端随意设置一个主页背景图片，即可解决该问题。

**Comment by brandonw3612** [comment]
Fixed in `v0.11.118`.
