### ISSUE TITLE
[FEATURE] 请求支持 Last.fm Scrobble

### ISSUE THREAD

**Issue by txyyh** [brandonw3612/LyricEase#7]
## 你的建议

希望可以支持 Last.fm Scrobble，抓取正在播放的歌曲信息并向 Last.fm 推送
## 该建议的实现方式

[Last.fm API Docs](https://www.last.fm/api/scrobbling)

目前已有一些实现可供参考
[Pano Scrobbler](https://github.com/kawaiiDango/pScrobbler) [YesPlayMusic](https://github.com/qier222/YesPlayMusic/blob/master/src/api/lastfm.js) [Last.fm-Scrubbler-WPF](https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF) [foo_scrobble](https://github.com/gix/foo_scrobble)

**Comment by brandonw3612** [comment]
已加入计划。

**Comment by brandonw3612** [comment]
您好，我们将在下一个预览体验版本中加入对 Last.fm 听歌打卡功能的支持。如果您愿意配合我们测试相关功能，请确保您已加入预览计划（非 Windows 预览体验计划）。关于该计划的详细信息，请通过电子邮件地址 brandonw3612@outlook.com 与我们联系。别忘了附上您的微软账号邮箱地址。如果您对该功能有其他更为详细的建议，欢迎在此 issue 下进行回复。

**Comment by brandonw3612** [comment]
v0.11.114 已支持。
