### ISSUE TITLE
[FEATURE] 请求添加UnblockNeteaseMusic功能

### ISSUE THREAD

**Issue by Cryberghost** [brandonw3612/LyricEase#70]
### [](https://github.com/nondanee/UnblockNeteaseMusic#%E8%BF%90%E8%A1%8C)特征

- 使用 QQ / 虾米 / 百度 / 酷狗 / 酷我 / 咪咕 / JOOX 音源替换变灰歌曲链接 (默认仅启用一、五、六)
- 为请求增加 X-Real-IP 参数解锁海外限制，支持指定网易云服务器 IP，支持设置上游 HTTP / HTTPS 代理
- 完整的流量代理功能 (HTTP / HTTPS)，可直接作为系统代理 (同时支持 PAC)

**Comment by brandonw3612** [comment]
我们这边是不会提供任何版权敏感操作的

**Comment by Cryberghost** [comment]
懂

**Comment by Cryberghost** [comment]
> 我们这边是不会提供任何版权敏感操作的

懂
