### ISSUE TITLE
动态磁贴

### ISSUE THREAD

**Issue by tjddbc** [brandonw3612/LyricEase#73]
老哥有兴趣加个动态磁贴吗？

**Comment by brandonw3612** [comment]
如果翻看一下更新记录的话，其实是可以看到在 Windows 11 发布前我们是支持 Windows 10 动态磁贴的。
但是随着 Windows 系统迭代和我们调查得知使用频率并不高，我们在 2021 年第三季度（即 Windows 10 向 Windows 11 过渡期间）逐渐移除了磁贴的相关功能。
很遗憾地告诉您，我们不再计划将磁贴带回 LyricEase，但最近通过新闻了解到微软似乎在计划向第三方软件开放 Windows 11 平台仪表板 Dashboard 中的小组件 Widgets 功能，如果可以实现，我们将会在相关文档公布后跟进小组件的实现。

**Comment by brandonw3612** [comment]
如果翻看一下更新记录的话，其实是可以看到在 Windows 11 发布前我们是支持 Windows 10 动态磁贴的。
但是随着 Windows 系统迭代和我们调查得知使用频率并不高，我们在 2021 年第三季度（即 Windows 10 向 Windows 11 过渡期间）逐渐移除了磁贴的相关功能。
很遗憾地告诉您，我们不再计划将磁贴带回 LyricEase，但最近通过新闻了解到微软似乎在计划向第三方软件开放 Windows 11 平台仪表板 Dashboard 中的小组件 Widgets 功能，如果可以实现，我们将会在相关文档公布后跟进小组件的实现。
