### ISSUE TITLE
亿点建议

### ISSUE THREAD

**Issue by Kylinbaba** [brandonw3612/LyricEase#74]
![4$AD398BRAC4SH~_)L)MNKT](https://user-images.githubusercontent.com/78674584/163726639-dd34d5e2-d106-4eae-8c9c-3ebb4d99b2cb.png)
![屏幕截图 2022-04-18 015602](https://user-images.githubusercontent.com/78674584/163726647-cb86c751-caf0-4b6a-9f64-628ce1eb19d5.png)
希望加入最小化到托盘 和适配win11的 播放菜单 
还有 整体流畅性不是很好 
祝越做越好 很喜欢！！！

**Comment by brandonw3612** [comment]
1. 请及时修改此 issue 的标题，表意不明的无效标题容易给社区其他人造成困扰；
2. 最小化到托盘实现不了，duplicate of #20 ；
3. Windows 系统媒体传输控件默认支持，如果不显示基本就是 Windows 的问题了，可尝试重启软件或系统解决；
4. 流畅性问题，目前有性能优化的计划。
