### ISSUE TITLE
[FEATURE] 建议加入退出lyricEase时自动退出热词APP的功能

### ISSUE THREAD

**Issue by Curious-r** [brandonw3612/LyricEase#75]
## 你的建议

建议加入退出lyricEase时自动退出热词APP的功能
## 该建议的实现方式

在"设置—交互"中“桌面歌词”条目下添加子选项：“退出本应用时自动关闭热词”
![image](https://user-images.githubusercontent.com/19733878/163795149-a5efc059-628c-43a3-9055-bbbbd50973d9.png)

## 附加信息

递归关闭.jpg（误

**Comment by brandonw3612** [comment]
不是我想关就能关的。要《热词》开放接口给我们才行。
请自行联系《热词》开发者。
