### ISSUE TITLE
[BUG] 检查更新

### ISSUE THREAD

**Issue by BalconyJH** [brandonw3612/LyricEase#76]
## 错误描述

启动软件触发自动检测更新，因某些原因检查失败并触发弹窗但不影响软件内正常使用
## 复现步骤

直接进入软件第一屏后再进行后台检测更新
## 屏幕截图 / 屏幕录制

![image](https://user-images.githubusercontent.com/73932916/164120970-48c49ca9-ffeb-4ee6-816a-86c1d22c88d1.png)

## 设备, Windows 和 LyricEase
 - 设备型号  :930QCG
 - Windows 版本号  :Windows 11 22000.613
 - Windows SKU  :pro
 - 是否为预览体验计划  : 否
 - LyricEase 版本号  :0.11.116

**Comment by brandonw3612** [comment]
1. 及时修改标题，表意不明；
2. 这算bug吗？
