### ISSUE TITLE
[FEATURE] 希望可以支持跟随系统的强调色设置

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [brandonw3612/LyricEase#77]
## 建议
希望可以支持系统的强调色设置（Accent Color），类似目前Windows 11媒体播放器的功能
![image](https://user-images.githubusercontent.com/45261195/164180999-f683456c-9bbf-47ce-a429-bb4b852a0d25.png)

**Comment by brandonw3612** [comment]
无计划提供
