### ISSUE TITLE
[BUG] 某些情况下复数 AudioTicket 同时播放

### ISSUE THREAD

**Issue by kengwang** [brandonw3612/LyricEase#8]
## 错误描述
某些情况下有复数 AudioTicket 在后(前)台同时播放且无法停止后台播放的

## 复现步骤

随意点开一个歌单(等拥有多个 Track 的), 进入歌词页面点击播放列表,
快速点击列表项将会有同点击次数的播放
同时点按暂停后之后暂停其中一个,不会暂停掉后台播放的

## 预期结果

不会同时播放那么多.

## 屏幕截图 / 屏幕录制

https://cdn.jsdelivr.net/gh/kengwang/CDN@main/2022-01-26%2014-59-59_x264.mp4

## Windows 和 LyricEase
 - Windows 版本号 Windows 11 (21H2) 22000.466
 - Windows SKU: 专业版
 - 是否为预览体验计划  : 否
 - LyricEase 版本号  : 0.9.94

## 附加信息
不知道该提到 PlaybackEngine 还是这里, 个人感觉应该是在 PlayBackEngine 上搞

**Comment by brandonw3612** [comment]
已修复. 月末推送.

**Comment by kengwang** [comment]
再小小的说一个关于 UX 的问题.
主要是因为在歌单页面需要双击才播放所以下意识的会认为双击才会播放, 因而在播放列表会下意识双击就复现出了此问题
可能有点个人习惯的加成......

**Comment by kengwang** [comment]
Fixed in V0.10.99
