### ISSUE TITLE
进入软件后提示网络服务错误

### ISSUE THREAD

**Issue by tangqiu0205** [brandonw3612/LyricEase#82]
## 错误描述

<img width="406" alt="image" src="https://user-images.githubusercontent.com/37826977/165669910-07d55314-0de4-4318-9b9b-0c6b1c0eb080.png">

## 复现步骤

1: 已开启网络回环
2: vpn开启与否进入都会提示.
## 设备, Windows 和 LyricEase
 - 设备型号  :
 - Windows 版本号  :
 - Windows SKU  :
 - 是否为预览体验计划  : 
 - LyricEase 版本号  :

**Comment by brandonw3612** [comment]
是否已参考 https://brandonw3612.github.io/LyricEase/faq.html ？

**Comment by tangqiu0205** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/37826977/166090009-8e838124-8e3d-4a5c-a710-6efc8c72a1eb.png">
这个命令也用了CheckNetIsolation.exe loopbackexempt -a -p=S-1-15-2-3740683252-4218607605-2448778852-3644121063-1212457277-1263217692-2375173846

**Comment by tangqiu0205** [comment]
卸载重装就好了.
