### ISSUE TITLE
建议增加【关闭到托盘】功能

### ISSUE THREAD

**Issue by hmr233** [brandonw3612/LyricEase#85]
而不是点击关闭后，程序直接退出
![截图_2022-04-30_10-46-16 1616](https://user-images.githubusercontent.com/67228631/166087601-c4ba8346-29c1-4650-842b-1b57dabc2c48.png)

**Comment by kengwang** [comment]
Dup #42
Please refer: https://github.com/brandonw3612/LyricEase/issues/42#issuecomment-1065786276

**Comment by kengwang** [comment]
Dup #20 
Please Refer: https://github.com/brandonw3612/LyricEase/issues/20#issuecomment-1030868755
