### ISSUE TITLE
希望增加歌词界面关闭模糊歌词功能呢

### ISSUE THREAD

**Issue by wanan1234** [brandonw3612/LyricEase#87]
增加关闭歌词模糊的选项
每次歌词都是模糊的，想看全部的歌词非常不方便，而且歌词模糊而又想看清歌词的时候头会很晕，建议增加关闭和开启的功能让使用者自己选择是否模糊歌词

**Comment by brandonw3612** [comment]
应用内设置 - 性能与体验 - 平衡(默认)。
默认就是平衡模式，非手动设置不会有歌词模糊的。
