### ISSUE TITLE
[BUG] 音频错误

### ISSUE THREAD

**Issue by Secular2020** [brandonw3612/LyricEase#88]
## 错误描述
错误提示：Audio node creation error: FormatNotSupported. 

## 复现步骤
正常列表播放MP3音乐产生的提示
以弹窗形式提示的

之前两个版本也有这个提示

## 设备, Windows 和 LyricEase
 - 设备型号 
 - 神州 ZX8-CP5S1
 - Windows 版本号
 - Windows11 22000.652  64位
 - Windows SKU
 - 专业版
 - 是否为预览体验计划
 - 否
 - LyricEase 版本号
 - 0.11.116

**Comment by kengwang** [comment]
字面意思, 文件编码不支持
如果可以的话发一下歌曲 ID 以及对应的音质以便更好追踪
