### ISSUE TITLE
[FEATURE] 专辑分 Disc

### ISSUE THREAD

**Issue by kengwang** [brandonw3612/LyricEase#9]
## 你的建议

对于专辑有些分了 Disc, Index 是在 Disc 中的 Index 而不是专辑

有些地方看上去不然很怪......

![image](https://user-images.githubusercontent.com/30862240/151121302-777ec81b-e020-419f-b5dd-3a60c56501e4.png)

(测试专辑: https://music.163.com/#/album?id=97767168 )

## 该建议的实现方式

可以稍微个分组

**Comment by kengwang** [comment]
反观网易云音乐的做法:
网页端 / PC 端: 无视了 Disc 以及 Index 的存在, 直接按照序号递加.
手机端: 有分组 Disc 并且有 Disc 名称

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/158013504-938f7714-f0a3-48e1-971d-03c2a6521682.png)
已在 Beta 通道收到更新
V 0.10.108

**Comment by brandonw3612** [comment]
v0.11.114 已支持。
