### ISSUE TITLE
[FEATURE] 歌词滚动希望复刻Apple Music动效

### ISSUE THREAD

**Issue by CMYMingyuChen** [brandonw3612/LyricEase#93]
## 你的建议

歌词换行时切换仍比较生硬，换行时候没有带动下面一起动起来，希望在非线性动画上继续努力，谢谢
## 该建议的实现方式

参照Apple Music动效复刻
## 附加信息

我的表述不是很准确，不是行内人，请多包涵。

**Comment by WinTerminal** [comment]
还有一点就是，歌词最顶上和最底下不显示完整时 会被一刀切，很不自然

**Comment by brandonw3612** [comment]
好。怎么实现？
