### ISSUE TITLE
[BUG] 应用运行时阻止系统休眠

### ISSUE THREAD

**Issue by ShiroAsrm** [brandonw3612/LyricEase#94]
## 错误描述

就算是暂停播放后，软件仍会占用声卡导致系统无法休眠
## 复现步骤

打开软件，尝试休眠，无果， powercfg /requests 发现声卡得到占用，关闭软件后不再占用
## 预期结果

暂停后不再占用声卡
## 设备, Windows 和 LyricEase
 - 设备型号  :
 - Windows 版本号  : Win11 22000.675
 - Windows SKU  :ProWorkstation
 - 是否为预览体验计划  : 否
 - LyricEase 版本号  : 0.11.116

**Comment by brandonw3612** [comment]
不做。会导致音频模块性能下降。
