### ISSUE TITLE
[BUG] 播放hires无损时发生音频慢放，无法正常播放

### ISSUE THREAD

**Issue by xsm1997** [brandonw3612/LyricEase#96]
## 错误描述

网易云已支持hires无损，在尝试播放hires无损时，会发生音频慢放（采样拉伸），无法正常播放。

## 复现步骤

1. 登陆会员网易云账号
2. 打开无损播放开关
3. 播放一首hires无损歌曲（如https://music.163.com/song?id=1883896216 ）

## 预期结果

音频正常播放

## 设备, Windows 和 LyricEase
 - 设备型号  : MS-7C94
 - Windows 版本号  : Windows 11 Insider Slow 22H2 22621.1
 - Windows SKU  :专业版
 - 是否为预览体验计划  : 是
 - LyricEase 版本号  : 0.11.116

**Comment by xsm1997** [comment]
#84 是hires的feature request，但是目前的版本无法区分无损和hires无损，打开无损播放开关后，如果播放的歌曲提供hires版本，就会发生以上bug，无法正常播放。

**Comment by kengwang** [comment]
Hello，我这边尝试了一下，其他的我目前已知的 Hi-Res 歌曲（[1859652717](https://music.163.com/#/song?id=1859652717)）可以正常播放。而[タクト](https://music.163.com/#/song?id=1883896216) 确实无法播放。

![image](https://user-images.githubusercontent.com/30862240/169648185-3c8590d8-bf26-4b77-b689-0e787bd646fa.png)

目前尝试了一下，是 AudioGraph 本身的问题（ LyricEase 目前使用 AudioGraph 播放），就算把文件下载了下来也无法正常使用 AudioGraph 播放 （测试方式：`Universal Windows Platform Sample - AudioCreation`），这个只能说是微软背锅了。

**Comment by xsm1997** [comment]
好的，感谢回复，先关闭issue了。
